import { Header } from '@/components/header';
import { ClaimCenter } from '@/components/bags/claim-center';

export default function EarningsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-deepNavy">
      <Header />
      <main className="flex-1 container mx-auto px-4 md:px-6 py-12">
        <div className="mb-12 max-w-2xl">
          <h1 className="font-display text-4xl font-bold tracking-tight mb-4">Earnings</h1>
          <p className="text-lg text-white/60 leading-relaxed">
            Claim your share of fees generated by the Bags ecosystem tokens you stake or create.
          </p>
        </div>
        
        <ClaimCenter />
      </main>
    </div>
  );
}
